-- Insert Actors
INSERT INTO Actors (actor_id, name) VALUES
(1, 'Leonardo DiCaprio'),
(2, 'Joseph Gordon-Levitt'),
(3, 'Elliot Page'),
(4, 'Christian Bale'),
(5, 'Heath Ledger'),
(6, 'Michael Caine'),
(7, 'Anne Hathaway'),
(8, 'Jessica Chastain'),
(9, 'Keanu Reeves'),
(10, 'Laurence Fishburne'),
(11, 'John Travolta'),
(12, 'Uma Thurman'),
(13, 'Samuel L. Jackson'),
(14, 'Russell Crowe'),
(15, 'Joaquin Phoenix'),
(16, 'Brad Pitt'),
(17, 'Edward Norton'),
(18, 'Tim Robbins'),
(19, 'Morgan Freeman'),
(20, 'Tom Hanks'),
(21, 'Robin Wright'),
(22, 'Marlon Brando'),
(23, 'Al Pacino'),
(24, 'James Caan'),
(25, 'Elijah Wood'),
(26, 'Ian McKellen'),
(27, 'Viggo Mortensen'),
(28, 'Sam Neill'),
(29, 'Jeff Goldblum'),
(30, 'Mark Hamill'),
(31, 'Harrison Ford'),
(32, 'Carrie Fisher'),
(33, 'Kate Winslet'),
(34, 'Sam Worthington'),
(35, 'Zoe Saldana'),
(36, 'Robert Downey Jr.'),
(37, 'Chris Evans'),
(38, 'Scarlett Johansson'),
(39, 'Hugh Jackman'),
(40, 'Matt Damon'),
(41, 'Jack Nicholson'),
(42, 'Jonah Hill'),
(43, 'Robert De Niro'),
(44, 'Ray Liotta'),
(45, 'Jodie Foster'),
(46, 'Anthony Hopkins'),
(47, 'Mel Gibson'),
(48, 'Michael Clarke Duncan'),
(49, 'Liam Neeson');